import { test } from "../../../fixtures.ts";
import { Helpers } from "../../../../common/helpers.ts";
import { AdminAddLocalAuthority } from "../../../../journeys/manageCases/caseProgression/addLocalAuthority/adminAddLocalAuthority.ts";
import Config from "../../../../utils/config.utils.ts";

test.use({ storageState: Config.sessionStoragePath + "caseWorker.json" });

test.describe("Add local authority event for C100 case tests as a Local Authority User.", () => {
  let ccdRef: string = "";

  test.beforeEach(async ({ page, browser, caseEventUtils }) => {
    ccdRef = await caseEventUtils.createCACaseSendToGatekeeper(browser);
    await Helpers.goToCase(
      page,
      Config.manageCasesBaseURLCase,
      ccdRef,
      "Summary",
    );
  });

  /**
   * TEST FLOW — Add Local Authority + LA Manage Documents + Court Admin task review
   *
   * LOGINS USED (3 sessions across separate browser windows):
   *   1. Court Admin / Caseworker  — default `page`, pre-authenticated via
   *      storageState (caseWorker.json). Creates the C100 case (beforeEach) and
   *      runs the "Add local authority" event.
   *   2. Local Authority user      — fresh window, fresh IDAM sign-in to Manage
   *      Organisation (signInLongLivedUser). Accepts the shared case and uploads
   *      documents. Same context is reused for Manage Cases (no second login).
   *   3. Court Admin / Caseworker  — second pre-authenticated window. Re-opens
   *      the case to verify the review tasks generated by the LA uploads.
   *
   * SETUP (beforeEach):
   *   - Create a C100 case and send it to gatekeeping (Gatekeeping state).
   *   - Open the case Summary tab as the court admin.
   *
   * COURT ADMIN — Add local authority (page 1):
   *   - Trigger "Add local authority" event; validate event page contents.
   *   - Search/select the LA organisation; validate Submit page (org details).
   *   - Submit; validate Confirm page.
   *   - Open Summary tab; validate the Local Authority section shows the org.
   *
   * LOCAL AUTHORITY — accept case & upload documents (STEPS 1-13):
   *   - STEP 1:  Sign in to Manage Organisation as the LA user.
   *   - STEP 2:  Open the org Cases list; validate org caption + "Cases" heading/link.
   *   - STEP 3:  Filter by case reference; validate "1 PRLAPPS" result + results table.
   *   - STEP 4:  Select the case and click Accept cases.
   *   - STEP 5:  Add recipient page — validate heading + case title; pick LA user email.
   *   - STEP 6:  Check-and-confirm page — validate heading, user-access block,
   *              email row, and "To be added" badge.
   *   - STEP 7:  Confirm — validate "Your selected cases have been updated" panel
   *              + "Go to Cases" link.
   *   - STEP 8:  Navigate to Manage Cases (re-uses the LA session).
   *   - STEP 9:  Open the case from the search results; validate ccd-case-header
   *              shows the hyphenated case reference.
   *   - STEP 10: Open the Summary tab.
   *   - STEP 11: Launch the "Manage documents" event.
   *   - STEP 12: Upload 5 LA documents (CIR 1 & 2, CIR extension, CIR transfer,
   *              Section 7) with the correct confidential/restricted flags.
   *   - STEP 13: Continue; validate the Manage documents Submit (Check-your-answers)
   *              page per document, then validate the Confirm page.
   * COURT ADMIN — review the generated tasks (STEPS 14-18):
   *   - STEP 14: Open Manage Cases as court admin; find the case via the 16-digit
   *              reference search; validate ccd-case-header.
   *   - STEP 15: Open the Tasks tab; validate "Review CIR Extension Request",
   *              "Review CIR Transfer Request" and "Review Documents" tasks
   *              (priority + Unassigned).
   *   - STEP 16: Assign the "Review Documents" task to self.
   *   - STEP 17: Launch the "Review Documents" event from Next steps.
   *   - STEP 18: Validate the reviewable-documents dynamic list shows the 4
   *              reviewable docs and excludes the non-reviewable Section 7 report.
   */
  test("Complete Add Local Authority with accessibility test. @nightly @regression @accessibility", async ({
    page,
    browser,
  }): Promise<void> => {
    await AdminAddLocalAuthority.adminAddLocalAuthority({
      page: page,
      browser: browser,
      accessibilityTest: false,
      organisationName: "Local Authority Private Law AAT Test Organisation",
      caseRef: ccdRef,
      localAuthorityUserEmail: Config.userCredentials.localAuthority.email,
    });
  });
});
