import { Page } from "@playwright/test";
import { Selectors } from "../../../../../common/selectors";
import { CommonReviewContent } from "../../../../../fixtures/citizen/createCase/C100/reviewPages/commonReviewContent";
import { Helpers } from "../../../../../common/helpers";
import AccessibilityTestHelper from "../../../../../common/accessibilityTestHelper";
import { TopMiroReviewContent } from "../../../../../fixtures/citizen/createCase/C100/reviewPages/topMiroReviewContent";

interface checkTextOptions {
  page: Page;
  accessibilityTest: boolean;
}

const statementOfTruthCheckbox: string = '#statementOfTruth'

export class ReviewPage {
  private static async checkCommonText({
    page,
    accessibilityTest
  }: checkTextOptions): Promise<void> {
    await page.locator(
      `${Selectors.GovukHeadingXL}:text-is("${CommonReviewContent.pageTitle}")`
    ).waitFor()
    await Promise.all([
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukBodyL}:text-is("${CommonReviewContent.bodyL}")`,
        1
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h1}:text-is("${CommonReviewContent.statementTitle}")`,
        1
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukHeadingM}:text-is("${CommonReviewContent.confirmationHeading}")`,
        1
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukInsetText}:text-is("${CommonReviewContent.insetText}")`,
        1
      ),
      Helpers.checkGroup(
        page,
        2,
        CommonReviewContent,
        'label',
        Selectors.GovukLabel
      ),
      Helpers.checkGroup(
        page,
        2,
        CommonReviewContent,
        'strong',
        Selectors.strong
      ),
    ]);
    if (accessibilityTest) {
      await AccessibilityTestHelper.run(page)
    }
  }

  private static async fillInFields(
    page: Page
  ): Promise<void> {
    await page.check(statementOfTruthCheckbox);
    await page.click(
      `${Selectors.GovukButton}:text-is("${CommonReviewContent.submitButton}")`
    );
  }

  public static async submitTopMiro({
    page,
    accessibilityTest
  }: checkTextOptions): Promise<void> {
    await this.checkCommonText({
      page: page,
      accessibilityTest: accessibilityTest
    })
    await Promise.all([
      Helpers.checkGroup(
        page,
        21,
         TopMiroReviewContent,
        'h2_govukheadingm_',
        `${Selectors.GovukHeadingM}`
      ),
      Helpers.checkGroup(
        page,
        13,
         TopMiroReviewContent,
        'dd_govuksummarylistvalue_',
        `${Selectors.GovukSummaryListValue}`
      ),
      Helpers.checkGroup(
        page,
        52,
         TopMiroReviewContent,
        'li_',
        `${Selectors.li}`
      ),
      Helpers.checkGroup(
        page,
        6,
         TopMiroReviewContent,
        'li_govukpaddingtop_',
        `${Selectors.li}`
      ),
      Helpers.checkGroup(
        page,
        14,
         TopMiroReviewContent,
        'h4_',
        `${Selectors.h4}`
      ),
      Helpers.checkGroup(
        page,
        21,
         TopMiroReviewContent,
        'p_',
        `${Selectors.p}`
      ),
      Helpers.checkGroup(
        page,
        3,
         TopMiroReviewContent,
        'h4_apptasklistsection_',
        `${Selectors.h4}`
      ),
      Helpers.checkGroup(
        page,
        6,
         TopMiroReviewContent,
        'div_govukpaddingbottom_',
        `${Selectors.div}`
      ),
      Helpers.checkGroup(
        page,
        7,
         TopMiroReviewContent,
        'div_govukpaddingtop_',
        `${Selectors.div}`
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whereDoTheChildrenLive}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAWrittenAgreementWithTheOtherPeopleInTheCaseThatYouWantTheCourtToReview}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whatAreYouAskingTheCourtToDo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_describeWhatYouWantTheCourtToDoRegardingTheChildrenInThisApplication}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doesYourSituationQualifyForAnUrgentFirstHearing}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areYouAskingForAWithoutNoticeHearing}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_fullName}")`,
        10
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_dateOfBirth}")`,
        10
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_gender}")`,
        10
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_ordersAppliedFor}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_stateEveryoneWhoHasParentalResponsibilityForExampletextExampletextAndHowTheyHaveParentalResponsibility}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areAnyOfTheChildrenKnownToSocialServices}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areAnyOfTheChildrenTheSubjectOfAChildProtectionPlan}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouOrAnyRespondentsHaveOtherChildrenWhoAreNotPartOfThisApplication}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doTheOtherPeopleNamedInThisApplicationtheRespondentsKnowAnyOfYourContactDetails}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_1}")`,
        1
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveYouChangedYourName}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_placeOfBirth}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_relationshipToExampletextExampletext}")`,
        6
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_addressDetails}")`,
        6
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_contactDetailsOfExampletextExampletext}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_canTheCourtLeaveYouAVoicemail}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_contactPreferences}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveTheyChangedTheirName}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_email}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_telephoneNumber}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_isThereAnyoneElseWhoShouldKnowAboutYourApplication}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whoDoesExampletextExampletextMainlyLiveWith}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_exampletextExampletextsLivingArrangements}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveTheChildrenBeenInvolvedInACourtCase}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveYouHadACourtOrderMadeForYourProtection}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_provideDetailsOfCourtCasesYouOrTheChildrenHaveBeenInvolvedIn}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_childArrangementsOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_emergencyProtectionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_supervisionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_careOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_childAbductionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_aContactOrResidenceOrdersection8ChildrenAct1989MadeWithinProceedingsForADivorceOrDissolutionOfACivilPartnership}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_aContactOrResidenceOrdersection8ChildrenAct1989MadeInConnectionWithAnAdoptionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_childMaintenanceOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_financialOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_nonmolestationOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_occupationOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_forcedMarriageProtectionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_restrainingOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_otherInjunctionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_undertakingOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_otherOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAnyConcernsForYourSafetyOrTheSafetyOfTheChildren}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whoAreYouConcernedAbout}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whatTypeOfBehaviourHaveTheChildrenExperiencedOrAreAtRiskOfExperiencing}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeThePhysicalAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeThePsychologicalAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheEmotionalAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheSexualAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheFinancialAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whyDoYouThinkTheChildrenMayBeAbductedOrKeptOutsideTheUkWithoutYourConsent}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whereAreTheChildrenNow}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doAnyOfTheChildrenHaveAPassport}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_hasThePassportOfficeBeenNotified}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveTheChildrenBeenAbductedOrKeptOutsideTheUkWithoutYourConsentBefore}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_provideDetailsOfThePreviousAbductions}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_wereThePolicePrivateInvestigatorsOrAnyOtherOrganisationInvolved}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeThePhysicalAbuseIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeThePsychologicalAbuseIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheEmotionalAbuseIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheSexualAbuseIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheConcernsIfYouFeelAbleTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveTheChildrenBeenImpactedByDrugAlcoholOrSubstanceAbuse}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAnyOtherConcernsAboutTheChildrensSafetyAndWellbeing}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whatDoYouWantTheCourtToDoToKeepYouAndTheChildrenSafe}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouAgreeToTheChildrenSpendingTimeWithTheOtherPeopleInThisApplication}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouAgreeToTheOtherPeopleInThisApplicationBeingInTouchWithTheChildrenInOtherWays}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areTheChildrensLivesMainlyBasedOutsideOfEnglandAndWales}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areTheChildrensParentsorAnyoneSignificantToTheChildrenMainlyBasedOutsideOfEnglandAndWales}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_couldAnotherPersonInTheApplicationApplyForASimilarOrderInACountryOutsideEnglandOrWales}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_hasAnotherCountryAskedorBeenAskedForInformationOrHelpForTheChildren}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_wouldYouBeAbleToTakePartInHearingsByVideoAndPhone}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAnyLanguageRequirements}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouOrTheChildrenNeedSpecialArrangementsAtCourt}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAPhysicalMentalOrLearningDisabilityOrHealthConditionThatMeansYouNeedSupportDuringYourCase}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedDocumentsInAnAlternativeFormat}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedHelpCommunicatingAndUnderstanding}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedToBringSupportWithMeToACourtHearing}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedSomethingToFeelComfortableDuringACourtHearing}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedHelpTravellingToOrMovingAroundCourtBuildings}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouNeedHelpWithPayingTheFeeForThisApplication}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_enterYourHelpWithFeesReferenceNumber}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_yes}")`,
        64
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_exampletextExampletext}")`,
        15
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_12October2008}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_male}")`,
        5
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_exampletext}")`,
        7
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_6November2002}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_swansea}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_mother}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_janeDoe}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_decideWhoTheChildrenLiveWithAndWhen}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_decideHowMuchTimeTheChildrenSpendWithEachPerson}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_changingTheChildrensNamesOrSurname}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_allowingMedicalTreatmentToBeCarriedOutOnTheChildren}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_takingTheChildrenOnHoliday}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_relocatingTheChildrenToADifferentAreaInEnglandAndWales}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_relocatingTheChildrenOutsideOfEnglandAndWalesincludingScotlandAndNorthernIreland}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_aSpecificHolidayOrArrangement}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_whatSchoolTheChildrenWillGoTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_aReligiousIssue}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_medicalTreatment}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_returningTheChildrenToYourCare}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_email}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_exampletextExampletext}")`,
        15
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_janeDoe}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_mother}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_visitToCourtBeforeTheHearing}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_iNeedDocumentsInAnAlternativeFormat}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_iNeedHelpCommunicatingAndUnderstanding}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_iNeedHelpTravellingToOrMovingAroundCourtBuildings}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_otherLoremIpsumOther}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_changingTheChildrensNamesOrSurname}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_allowingMedicalTreatmentToBeCarriedOutOnTheChildren}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_takingTheChildrenOnHoliday}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_relocatingTheChildrenToADifferentAreaInEnglandAndWales}")`,
        4
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_relocatingTheChildrenOutsideOfEnglandAndWalesincludingScotlandAndNorthernIreland}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_aSpecificHolidayOrArrangement}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_whatSchoolTheChildrenWillGoTo}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_aReligiousIssue}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_medicalTreatment}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_returningTheChildrenToYourCare}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_physicalAbuse}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_psychologicalAbuse}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_emotionalAbuse}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_sexualAbuse}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_financialAbuse}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_somethingElse}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_details}")`,
        24
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whichCourtIssuedTheOrderoptional}")`,
        16
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_caseNumberoptional}")`,
        16
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whatDateWasItMadeoptional}")`,
        16
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_isThisACurrentOrderoptional}")`,
        16
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whatDateDidItEndoptional}")`,
        16
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_doYouHaveACopyOfTheOrderoptional}")`,
        16
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whichChildrenAreYouConcernedAboutoptional}")`,
        5
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_describeTheBehavioursYouWouldLikeTheCourtToBeAwareOfoptional}")`,
        11
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whenDidThisBehaviourStartAndHowLongDidItContinueoptional}")`,
        11
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_isTheBehaviourOngoingoptional}")`,
        11
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_haveYouEverAskedForHelpFromAProfessionalPersonOrAgencyoptional}")`,
        11
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_exampletext}")`,
        7
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_yes}")`,
        64
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_bs19f99999}")`,
        16
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10July2016}")`,
        5
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10July2017}")`,
        6
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_automatedChildAbductionOrderCourt}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10June2015}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10June2017}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_18August2015}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_18August2018}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_automatedOccupationOrderCourt}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10July2018}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10July2014}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_loremIpsumStartDetails}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_apptasklistsection_child1}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.div}:text-is("${TopMiroReviewContent.div_govukpaddingbottom_yes}")`,
        64
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_childArrangementsOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_emergencyProtectionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_supervisionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_careOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_childAbductionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_aContactOrResidenceOrdersection8ChildrenAct1989MadeWithinProceedingsForADivorceOrDissolutionOfACivilPartnership}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_aContactOrResidenceOrdersection8ChildrenAct1989MadeInConnectionWithAnAdoptionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_childMaintenanceOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_financialOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_nonmolestationOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_occupationOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_forcedMarriageProtectionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_restrainingOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_otherInjunctionOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_undertakingOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_otherOrder}")`,
        3
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.ul}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_otherOrder}")`,
        15
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.div}:text-is("${TopMiroReviewContent.div_govukpaddingtop_automatedPhysicalSeekHelpDetails}")`,
        2
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.div}:text-is("${TopMiroReviewContent.div_govukpaddingtop_automatedEmotionalSeekHelpDetails}")`,
        2
      ),
    ])
    await this.fillInFields(page)
  }
}