import { errors, Page } from "@playwright/test";
import { Selectors } from "../../../../../common/selectors";
import { CommonReviewContent } from "../../../../../fixtures/citizen/createCase/C100/reviewPages/commonReviewContent";
import { Helpers } from "../../../../../common/helpers";
import AccessibilityTestHelper from "../../../../../common/accessibilityTestHelper";
import { TopMiroReviewContent } from "../../../../../fixtures/citizen/createCase/C100/reviewPages/topMiroReviewContent";
import {
  SecondMiroReviewContent
} from "../../../../../fixtures/citizen/createCase/C100/reviewPages/secondMiroReviewContent";
import { CapitalizedRelationship } from "../../../../../common/types";


interface checkTextOptions {
  page: Page;
  accessibilityTest: boolean;
  reviewPageTopJourneyMotherFather: reviewPageTopJourneyMotherFather;
  relationshipType: CapitalizedRelationship
}

export type reviewPageTopJourneyMotherFather = "mother" | "father";

const statementOfTruthCheckbox: string = "#statementOfTruth";

export class ReviewPage {
  private static async checkCommonText({
                                         page,
                                         accessibilityTest,
                                       }: Partial<checkTextOptions>): Promise<void> {
    if (!page) {
      throw new Error();
    }
    await page
      .locator(
        `${Selectors.GovukHeadingXL}:text-is("${CommonReviewContent.pageTitle}")`,
      )
      .waitFor();
    await Promise.all([
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukBodyL}:text-is("${CommonReviewContent.bodyL}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h1}:text-is("${CommonReviewContent.statementTitle}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukHeadingM}:text-is("${CommonReviewContent.confirmationHeading}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${CommonReviewContent.insetText}")`,
        1,
      ),
      Helpers.checkGroup(
        page,
        2,
        CommonReviewContent,
        "label",
        Selectors.GovukLabel,
      ),
      Helpers.checkGroup(
        page,
        2,
        CommonReviewContent,
        "strong",
        Selectors.strong,
      ),
    ]);
    // if (accessibilityTest) {
    //   await AccessibilityTestHelper.run(page); #TODO Disabled pending PRL-6619 ticket
    // }
  }

  private static async fillInFields(page: Page): Promise<void> {
    await page.check(statementOfTruthCheckbox);
    await page.click(
      `${Selectors.GovukButton}:text-is("${CommonReviewContent.submitButton}")`,
    );
  }

  public static async submitTopMiro({
                                      page,
                                      accessibilityTest,
                                      reviewPageTopJourneyMotherFather,
    relationshipType
                                    }: checkTextOptions): Promise<void> {
    await this.checkCommonText({
      page,
      accessibilityTest,
      reviewPageTopJourneyMotherFather,
      relationshipType
    });
    await Promise.all([
      Helpers.checkGroup(
        page,
        21,
        TopMiroReviewContent,
        "h2_govukheadingm_",
        `${Selectors.GovukHeadingM}`,
      ),
      Helpers.checkGroup(
        page,
        13,
        TopMiroReviewContent,
        "dd_govuksummarylistvalue_",
        `${Selectors.GovukSummaryListValue}`,
      ),
      Helpers.checkGroup(
        page,
        52,
        TopMiroReviewContent,
        "li_",
        `${Selectors.li}`,
      ),
      Helpers.checkGroup(
        page,
        6,
        TopMiroReviewContent,
        "li_govukpaddingtop_",
        `${Selectors.li}`,
      ),
      Helpers.checkGroup(
        page,
        14,
        TopMiroReviewContent,
        "h4_",
        `${Selectors.h4}`,
      ),
      Helpers.checkGroup(
        page,
        21,
        TopMiroReviewContent,
        "p_",
        `${Selectors.p}`,
      ),
      Helpers.checkGroup(
        page,
        3,
        TopMiroReviewContent,
        "h4_apptasklistsection_",
        `${Selectors.h4}`,
      ),
      Helpers.checkGroup(
        page,
        6,
        TopMiroReviewContent,
        "div_govukpaddingbottom_",
        `${Selectors.div}`,
      ),
      Helpers.checkGroup(
        page,
        7,
        TopMiroReviewContent,
        "div_govukpaddingtop_",
        `${Selectors.div}`,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whereDoTheChildrenLive}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAWrittenAgreementWithTheOtherPeopleInTheCaseThatYouWantTheCourtToReview}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whatAreYouAskingTheCourtToDo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_describeWhatYouWantTheCourtToDoRegardingTheChildrenInThisApplication}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doesYourSituationQualifyForAnUrgentFirstHearing}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areYouAskingForAWithoutNoticeHearing}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_fullName}")`,
        5,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_dateOfBirth}")`,
        5,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_gender}")`,
        5,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_ordersAppliedFor}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_stateEveryoneWhoHasParentalResponsibilityForExampletextExampletextAndHowTheyHaveParentalResponsibility}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areAnyOfTheChildrenKnownToSocialServices}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areAnyOfTheChildrenTheSubjectOfAChildProtectionPlan}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouOrAnyRespondentsHaveOtherChildrenWhoAreNotPartOfThisApplication}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doTheOtherPeopleNamedInThisApplicationtheRespondentsKnowAnyOfYourContactDetails}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_1}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveYouChangedYourName}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_placeOfBirth}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_relationshipToExampletextExampletext}")`,
        3,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_addressDetails}")`,
        3,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_contactDetailsOfExampletextExampletext}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_canTheCourtLeaveYouAVoicemail}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_contactPreferences}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveTheyChangedTheirName}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_email}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_telephoneNumber}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_isThereAnyoneElseWhoShouldKnowAboutYourApplication}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whoDoesExampletextExampletextMainlyLiveWith}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_exampletextExampletextsLivingArrangements}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveTheChildrenBeenInvolvedInACourtCase}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveYouHadACourtOrderMadeForYourProtection}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_provideDetailsOfCourtCasesYouOrTheChildrenHaveBeenInvolvedIn}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_childArrangementsOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_emergencyProtectionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_supervisionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_careOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_childAbductionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_aContactOrResidenceOrdersection8ChildrenAct1989MadeWithinProceedingsForADivorceOrDissolutionOfACivilPartnership}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_aContactOrResidenceOrdersection8ChildrenAct1989MadeInConnectionWithAnAdoptionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_childMaintenanceOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_financialOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_nonmolestationOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_occupationOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_forcedMarriageProtectionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_restrainingOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_otherInjunctionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_undertakingOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_otherOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAnyConcernsForYourSafetyOrTheSafetyOfTheChildren}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whoAreYouConcernedAbout}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whatTypeOfBehaviourHaveTheChildrenExperiencedOrAreAtRiskOfExperiencing}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeThePhysicalAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeThePsychologicalAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheEmotionalAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheSexualAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheFinancialAbuseAgainstTheChildIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whyDoYouThinkTheChildrenMayBeAbductedOrKeptOutsideTheUkWithoutYourConsent}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whereAreTheChildrenNow}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doAnyOfTheChildrenHaveAPassport}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_hasThePassportOfficeBeenNotified}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveTheChildrenBeenAbductedOrKeptOutsideTheUkWithoutYourConsentBefore}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_provideDetailsOfThePreviousAbductions}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_wereThePolicePrivateInvestigatorsOrAnyOtherOrganisationInvolved}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeThePhysicalAbuseIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeThePsychologicalAbuseIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheEmotionalAbuseIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheSexualAbuseIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_brieflyDescribeTheConcernsIfYouFeelAbleTo}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_haveTheChildrenBeenImpactedByDrugAlcoholOrSubstanceAbuse}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAnyOtherConcernsAboutTheChildrensSafetyAndWellbeing}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_whatDoYouWantTheCourtToDoToKeepYouAndTheChildrenSafe}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouAgreeToTheChildrenSpendingTimeWithTheOtherPeopleInThisApplication}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouAgreeToTheOtherPeopleInThisApplicationBeingInTouchWithTheChildrenInOtherWays}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areTheChildrensLivesMainlyBasedOutsideOfEnglandAndWales}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_areTheChildrensParentsorAnyoneSignificantToTheChildrenMainlyBasedOutsideOfEnglandAndWales}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_couldAnotherPersonInTheApplicationApplyForASimilarOrderInACountryOutsideEnglandOrWales}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_hasAnotherCountryAskedorBeenAskedForInformationOrHelpForTheChildren}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_wouldYouBeAbleToTakePartInHearingsByVideoAndPhone}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAnyLanguageRequirements}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouOrTheChildrenNeedSpecialArrangementsAtCourt}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouHaveAPhysicalMentalOrLearningDisabilityOrHealthConditionThatMeansYouNeedSupportDuringYourCase}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedDocumentsInAnAlternativeFormat}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedHelpCommunicatingAndUnderstanding}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedToBringSupportWithMeToACourtHearing}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedSomethingToFeelComfortableDuringACourtHearing}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_iNeedHelpTravellingToOrMovingAroundCourtBuildings}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_doYouNeedHelpWithPayingTheFeeForThisApplication}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListKey}:text-is("${TopMiroReviewContent.dt_govuksummarylistkey_enterYourHelpWithFeesReferenceNumber}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_yes}")`,
        36,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_exampletextExampletext}")`,
        4,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_12October2008}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_male}")`,
        5,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_exampletext}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:has-text("${TopMiroReviewContent.dd_govuksummarylistvalue_November2002}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_swansea}")`,
        3,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_janeDoe}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_decideWhoTheChildrenLiveWithAndWhen}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_decideHowMuchTimeTheChildrenSpendWithEachPerson}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_changingTheChildrensNamesOrSurname}")`,
        4,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_allowingMedicalTreatmentToBeCarriedOutOnTheChildren}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_takingTheChildrenOnHoliday}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_relocatingTheChildrenToADifferentAreaInEnglandAndWales}")`,
        4,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_relocatingTheChildrenOutsideOfEnglandAndWalesincludingScotlandAndNorthernIreland}")`,
        4,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_aSpecificHolidayOrArrangement}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_whatSchoolTheChildrenWillGoTo}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_aReligiousIssue}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_medicalTreatment}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_returningTheChildrenToYourCare}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_email}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_exampletextExampletext}")`,
        6,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_janeDoe}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_visitToCourtBeforeTheHearing}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_iNeedDocumentsInAnAlternativeFormat}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_iNeedHelpCommunicatingAndUnderstanding}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_iNeedHelpTravellingToOrMovingAroundCourtBuildings}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_otherLoremIpsumOther}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_changingTheChildrensNamesOrSurname}")`,
        4,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_allowingMedicalTreatmentToBeCarriedOutOnTheChildren}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_takingTheChildrenOnHoliday}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_relocatingTheChildrenToADifferentAreaInEnglandAndWales}")`,
        4,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_relocatingTheChildrenOutsideOfEnglandAndWalesincludingScotlandAndNorthernIreland}")`,
        4,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_aSpecificHolidayOrArrangement}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_whatSchoolTheChildrenWillGoTo}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_aReligiousIssue}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_medicalTreatment}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_returningTheChildrenToYourCare}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_physicalAbuse}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_psychologicalAbuse}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_emotionalAbuse}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_sexualAbuse}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_financialAbuse}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingtop_somethingElse}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_details}")`,
        24,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whichCourtIssuedTheOrderoptional}")`,
        16,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_caseNumberoptional}")`,
        16,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whatDateWasItMadeoptional}")`,
        16,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_isThisACurrentOrderoptional}")`,
        16,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whatDateDidItEndoptional}")`,
        16,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_doYouHaveACopyOfTheOrderoptional}")`,
        16,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whichChildrenAreYouConcernedAboutoptional}")`,
        5,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_describeTheBehavioursYouWouldLikeTheCourtToBeAwareOfoptional}")`,
        11,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_whenDidThisBehaviourStartAndHowLongDidItContinueoptional}")`,
        11,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_isTheBehaviourOngoingoptional}")`,
        11,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_haveYouEverAskedForHelpFromAProfessionalPersonOrAgencyoptional}")`,
        11,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_yes}")`,
        39,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_bs19f99999}")`,
        16,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10July2016}")`,
        5,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10July2017}")`,
        6,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_automatedChildAbductionOrderCourt}")`,
        3,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10June2015}")`,
        3,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10June2017}")`,
        3,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_18August2015}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_18August2018}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_automatedOccupationOrderCourt}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10July2018}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_10July2014}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.p}:text-is("${TopMiroReviewContent.p_loremIpsumStartDetails}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.h4}:text-is("${TopMiroReviewContent.h4_apptasklistsection_child1}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.div}:text-is("${TopMiroReviewContent.div_govukpaddingbottom_yes}")`,
        12,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_childArrangementsOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_emergencyProtectionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_supervisionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_careOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_childAbductionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_aContactOrResidenceOrdersection8ChildrenAct1989MadeWithinProceedingsForADivorceOrDissolutionOfACivilPartnership}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_aContactOrResidenceOrdersection8ChildrenAct1989MadeInConnectionWithAnAdoptionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_childMaintenanceOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_financialOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_nonmolestationOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_occupationOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_forcedMarriageProtectionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_restrainingOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_otherInjunctionOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_undertakingOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.li}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_otherOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.ul}:text-is("${TopMiroReviewContent.li_govukpaddingbottom_otherOrder}")`,
        1,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.div}:text-is("${TopMiroReviewContent.div_govukpaddingtop_automatedPhysicalSeekHelpDetails}")`,
        2,
      ),
      Helpers.checkVisibleAndPresent(
        page,
        `${Selectors.div}:text-is("${TopMiroReviewContent.div_govukpaddingtop_automatedEmotionalSeekHelpDetails}")`,
        2,
      ),
    ]);
    if (reviewPageTopJourneyMotherFather === "mother") {
      await Promise.all([
        Helpers.checkVisibleAndPresent(
          page,
          `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_mother}")`,
          3,
        ),
        Helpers.checkVisibleAndPresent(
          page,
          `${Selectors.li}:text-is("${TopMiroReviewContent.li_mother}")`,
          1,
        ),
      ]);
    } else if (reviewPageTopJourneyMotherFather === "father") {
      await Promise.all([
        Helpers.checkVisibleAndPresent(
          page,
          `${Selectors.GovukSummaryListValue}:text-is("${TopMiroReviewContent.dd_govuksummarylistvalue_father}")`,
          3,
        ),
        Helpers.checkVisibleAndPresent(
          page,
          `${Selectors.li}:text-is("${TopMiroReviewContent.li_father}")`,
          1,
        ),
      ]);
    }
    await this.fillInFields(page);
  }

public static async submitSecondMiro({
  page,
  accessibilityTest,
                                       relationshipType
}: Partial<checkTextOptions>): Promise<void> {
  if (!page) {
    throw new Error();
  }
  await this.checkCommonText({
    page,
    accessibilityTest,
    relationshipType
  });
  await Promise.all([
    Helpers.checkGroup(
      page,
      25,
      SecondMiroReviewContent,
      "h2_",
      Selectors.h2,
    ),
    Helpers.checkGroup(
      page,
      87,
      SecondMiroReviewContent,
      "dt_",
      Selectors.dt,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dt}:text-is("${SecondMiroReviewContent.dt_whatTypeOfBehaviourHaveTheChildrenExperiencedOrAreAtRiskOfExperiencing}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dt}:text-is("${SecondMiroReviewContent.dt_haveTheyChangedTheirName}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dt}:text-is("${SecondMiroReviewContent.dt_placeOfBirth}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dt}:text-is("${SecondMiroReviewContent.dt_relationshipToExampletextExampletext}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dt}:text-is("${SecondMiroReviewContent.dt_addressDetails}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dt}:text-is("${SecondMiroReviewContent.dt_fullName}")`,
      5,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dt}:text-is("${SecondMiroReviewContent.dt_dateOfBirth}")`,
      5,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dt}:text-is("${SecondMiroReviewContent.dt_gender}")`,
      5,
    ),
    Helpers.checkGroup(
      page,
      14,
      SecondMiroReviewContent,
      "dd_",
      Selectors.dd,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_example}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_Other}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_janeDoe}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_swansea}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:has-text("${relationshipType}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_exampletextExampletext}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_12October2008}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_male}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_no}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.dd}:text-is("${SecondMiroReviewContent.dd_yes}")`,
      38,
    ),
    Helpers.checkGroup(
      page,
      87,
      SecondMiroReviewContent,
      "span_",
      Selectors.Span,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.Span}:text-is("${SecondMiroReviewContent.span_whatTypeOfBehaviourHaveTheChildrenExperiencedOrAreAtRiskOfExperiencing}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.Span}:text-is("${SecondMiroReviewContent.span_haveTheyChangedTheirName}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.Span}:text-is("${SecondMiroReviewContent.span_placeOfBirth}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.Span}:text-is("${SecondMiroReviewContent.span_relationshipToExampletextExampletext}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.Span}:text-is("${SecondMiroReviewContent.span_addressDetails}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.Span}:text-is("${SecondMiroReviewContent.span_fullName}")`,
      5,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.Span}:text-is("${SecondMiroReviewContent.span_dateOfBirth}")`,
      5,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.Span}:text-is("${SecondMiroReviewContent.span_gender}")`,
      5,
    ),
    Helpers.checkGroup(
      page,
      83,
      SecondMiroReviewContent,
      "li_",
      Selectors.li,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_otherLoremIpsumOther}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_visitToCourtBeforeTheHearing}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_somethingElse}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_physicalAbuse}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_psychologicalAbuse}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_emotionalAbuse}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_sexualAbuse}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_financialAbuse}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_exampletextExampletext}")`,
      6,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_aSpecificHolidayOrArrangement}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_whatSchoolTheChildrenWillGoTo}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_aReligiousIssue}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_medicalTreatment}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_changingTheChildrensNamesOrSurname}")`,
      4,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_allowingMedicalTreatmentToBeCarriedOutOnTheChildren}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_takingTheChildrenOnHoliday}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_relocatingTheChildrenToADifferentAreaInEnglandAndWales}")`,
      4,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_relocatingTheChildrenOutsideOfEnglandAndWalesincludingScotlandAndNorthernIreland}")`,
      4,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_decideWhoTheChildrenLiveWithAndWhen}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_decideHowMuchTimeTheChildrenSpendWithEachPerson}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.li}:text-is("${SecondMiroReviewContent.li_returningTheChildrenToYourCare}")`,
      2,
    ),
    Helpers.checkGroup(
      page,
      17,
      SecondMiroReviewContent,
      "h4_",
      Selectors.h4,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_child1}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_details}")`,
      26,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_whichCourtIssuedTheOrderoptional}")`,
      16,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_caseNumberoptional}")`,
      16,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_whatDateWasItMadeoptional}")`,
      16,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_isThisACurrentOrderoptional}")`,
      16,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_whatDateDidItEndoptional}")`,
      16,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_doYouHaveACopyOfTheOrderoptional}")`,
      16,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_whichChildrenAreYouConcernedAboutoptional}")`,
      5,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_describeTheBehavioursYouWouldLikeTheCourtToBeAwareOfoptional}")`,
      11,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_whenDidThisBehaviourStartAndHowLongDidItContinueoptional}")`,
      11,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_isTheBehaviourOngoingoptional}")`,
      11,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.h4}:text-is("${SecondMiroReviewContent.h4_haveYouEverAskedForHelpFromAProfessionalPersonOrAgencyoptional}")`,
      11,
    ),
    Helpers.checkGroup(page, 21, SecondMiroReviewContent, "p_", Selectors.p),
    Helpers.checkGroup(
      page,
      13,
      SecondMiroReviewContent,
      "div_",
      Selectors.div,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_exampletext}")`,
      6,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_loremIpsumStartDetails}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_10July2014}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_automatedOccupationOrderCourt}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_10July2018}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_18August2015}")`,
      2,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_automatedChildAbductionOrderCourt}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_10June2015}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_10June2017}")`,
      3,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_bs19f99999}")`,
      16,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_10July2016}")`,
      5,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_yes}")`,
      39,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_10July2017}")`,
      6,
    ),
    Helpers.checkVisibleAndPresent(
      page,
      `${Selectors.p}:text-is("${SecondMiroReviewContent.p_18August2018}")`,
      2,
    ),
  ]);
  await this.fillInFields(page);
}
}
