export enum ChildLocationContent {
  pageTitle = 'Why do you think the children may be abducted or kept outside the UK without your consent?',
  caption = 'Safety concerns',
  span = '!',
  strong = 'Contact the police or social services if a child you’re responsible for is at risk of being taken out of the UK without your consent.',
  headingS = 'Briefly explain your concerns, including:',
  li1 = 'Who might take them',
  li2 = 'Where they might be taken or kept',
  locationLabel = 'Where are the children now?',
  locationHint = 'If they’re outside England or Wales, include what country they’re in and how long they’ve been there. You don’t need to include any addresses.',
  sidebarLink1 = 'Guidance on parental child abduction',
  sidebarLink2 = 'Get help to return a child from abroad or arrange contact',
  sidebarLink3 = 'Stop a child from getting a passport',
  errorSummaryList1 = 'Explain why you think the children may be abducted or kept outside of the UK without your consent',
  errorSummaryList2 = 'Describe where the children are now',
  errorMessage1 = 'Explain why you think the children may be abducted or kept outside of the UK without your consent',
  errorMessage2 = 'Describe where the children are now',
  abductionReason = 'Automated Abduction Reason',
  childLocation = 'Automated Child Location'
}