import { test } from "@playwright/test";
import { C100 } from "../../../../journeys/citizen/createCase/C100/C100";
import Config from "../../../../config";
import IdamLoginHelper from "../../../../common/idamLoginHelper";

test.describe("C100 Citizen Application tests on the second MIRO set. @citizenFrontend @crossbrowserCitizenFrontend", (): void => {
  test.beforeEach(async ({ page }) => {
    await IdamLoginHelper.signInCitizenUser(
      page,
      Config.citizenFrontendBaseURL,
    );
  });
  test(`Test the second row of the second row c100 citizen journey with the following options:
    Not Accessibility Testing,
    Not Error Messaging,
    No Screening and Written Review
    Legal Representation: no
    Court Permission Needed: no
    Other proceedings: no to all
    child arrangement order details: no
    urgency and without notice: no
    gender: male
    people: yes
    Children Supervision: yesSpendTime
    People YesNoDontKnow: "yes",
    Others Know Applicants Contact: "yes",
    Private Details: yes,
    applicant Changed Name: yes,
    applicant Gender: "other",
    applicant Relationship: "grandparent",
    applicant Address Lookup: yes,
    app Address Lookup Successful: yes,
    applicant Prev Address 5Years: yes,
    applicant Email Telephone Voicemail: yes,
    applicant Digital Preference: yes,
    respondent Known DoB: yes,
    respondent Known Place Of Birth: yes,
    respondent Gender: "other",
    respondent Changed Name: "yes",
    resp Address 5Years: "yes",
    respondent Relationship: "grandparent",
    resp Address Lookup: yes,
    resp Address Lookup Successful: yes,
    resp Known Email And Phone: yes,
    yes No Other Person Details: yes,
    Other People Gender: "other",
    Other People Changed Name: "yes",
    Other People DoB Known: yes,
    Other Person Relationship: "grandparent",
    Child Mainly Lives With: "respondent",
    Children Safety Concerns: yes,
    Safety Concerns Yes NoToAll: yes,
    Children Have Passport: yes,
    More Than One Passport: yes,
    PassportOffice Notified: yes,
    Children Abducted Before: yes,
    Children Supervision: "yesSpendTime",
    yes No International Elements: yes,
    yes No Reasonable Adjustments: yes,
    Yes No Need Help With Fees: yes,
    Yes No Fees Applied: yes,`, async ({ page }): Promise<void> => {
    await C100.c100SecondMiroJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: true,
      c100CourtPermissionNeeded: true,
      yesNoOtherProceedings: true,
      urgencyAndWithoutNoticeAllOptionsYes: true,
      gender: "male",
      c100PeopleYesNoDontKnow: "yes",
      c100OthersKnowApplicantsContact: "yes",
      c100PrivateDetails: true,
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "grandparent",
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "yes",
      respAddress5Years: "yes",
      respondentRelationship: "grandparent",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "yes",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "grandparent",
      c100ChildMainlyLivesWith: "respondent",
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: true,
      c100YesNoFeesApplied: true,
    });
  });

  test(`Test the second row of the second row c100 citizen journey with the following options:
    Not Accessibility Testing,
    Yes Error Messaging,
    No Screening and Written Review
    Legal Representation: no
    Court Permission Needed: no
    Other proceedings: yes to all
    child arrangement order details: no
    urgency and without notice: no
    gender: female
    people: no
    Others Know Applicants Contact: "no",
    Private Details: yes,
    applicant Changed Name: no,
    applicant Gender: "other",
    applicant Relationship: "guardian",
    applicant Address Lookup: no,
    app Address Lookup Successful: no,
    applicant Prev Address 5Years: no,
    applicant Email Telephone Voicemail: no,
    applicant Digital Preference: no,
    respondent Known DoB: no,
    respondent Known Place Of Birth: no,
    respondent Gender: "female",
    respondent Changed Name: "no",
    resp Address 5Years: "no",
    respondent Relationship: "guardian",
    resp Address Lookup: no,
    resp Address Lookup Successful: no,
    resp Known Email And Phone: no,
    yes No Other Person Details: no,
    Other People Gender: "female",
    Other People Changed Name: "no",
    Other People DoB Known: no,
    Other Person Relationship: "guardian",
    Child Mainly Lives With: "respondent",
    Children Safety Concerns: no,
    Safety Concerns Yes NoToAll: no,
    Children Have Passport: no,
    More Than One Passport: no,
    PassportOffice Notified: no,
    Children Abducted Before: no,
    Children Supervision: "yesButSupervised",
    yes No International Elements: no,
    yes No Reasonable Adjustments: no,
    Yes No Need Help With Fees: no,
    Yes No Fees Applied: no,`, async ({ page }): Promise<void> => {
    await C100.c100SecondMiroJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: true,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: false,
      yesNoOtherProceedings: false,
      urgencyAndWithoutNoticeAllOptionsYes: false,
      gender: "female",
      c100PeopleYesNoDontKnow: "no",
      c100OthersKnowApplicantsContact: "no",
      c100PrivateDetails: false,
      applicantChangedName: false,
      applicantGender: "female",
      applicantRelationship: "guardian",
      applicantAddressLookup: false,
      appAddressLookupSuccessful: false,
      applicantPrevAddress5Years: false,
      applicantEmailTelephoneVoicemail: false,
      applicantDigitalPreference: false,
      respondentKnownDoB: false,
      respondentKnownPlaceOfBirth: false,
      respondentGender: "female",
      respondentChangedName: "no",
      respAddress5Years: "no",
      respondentRelationship: "guardian",
      respAddressLookup: false,
      respAddressLookupSuccessful: false,
      respKnownEmailAndPhone: false,
      yesNoOtherPersonDetails: false,
      c100OtherPeopleGender: "female",
      c100OtherPeopleChangedName: "no",
      c100OtherPeopleDoBKnown: false,
      c100OtherPersonRelationship: "guardian",
      c100ChildMainlyLivesWith: "respondent",
      c100ChildrenSafetyConcerns: false,
      c100SafetyConcernsYesNoToAll: false,
      c100ChildrenHavePassport: false,
      c100MoreThanOnePassport: false,
      c100PassportOfficeNotified: false,
      c100ChildrenAbductedBefore: false,
      c100ChildrenSupervision: "yesButSupervised",
      yesNoInternationalElements: false,
      yesNoReasonableAdjustments: false,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });
  test(`Test the second row of the second row c100 citizen journey with the following options:
    Accessibility Testing,
    Not Error Messaging,
    No Screening and Written Review
    Legal Representation: no
    Court Permission Needed: no
    Other proceedings: yes to all
    child arrangement order details: no
    urgency and without notice: no,
    gender: other
    people: yes
    Children Supervision: yesSpendTime
    People YesNoDontKnow: "yes",
    Others Know Applicants Contact: "yes",
    Private Details: yes,
    applicant Changed Name: yes,
    applicant Gender: "other",
    applicant Relationship: "grandparent",
    applicant Address Lookup: yes,
    app Address Lookup Successful: yes,
    applicant Prev Address 5Years: yes,
    applicant Email Telephone Voicemail: yes,
    applicant Digital Preference: yes,
    respondent Known DoB: yes,
    respondent Known Place Of Birth: yes,
    respondent Gender: "other",
    respondent Changed Name: "yes",
    resp Address 5Years: "yes",
    respondent Relationship: "grandparent",
    resp Address Lookup: yes,
    resp Address Lookup Successful: yes,
    resp Known Email And Phone: yes,
    yes No Other Person Details: yes,
    Other People Gender: "other",
    Other People Changed Name: "yes",
    Other People DoB Known: yes,
    Other Person Relationship: "grandparent",
    Child Mainly Lives With: "respondent",
    Children Safety Concerns: yes,
    Safety Concerns Yes NoToAll: yes,
    Children Have Passport: yes,
    More Than One Passport: yes,
    PassportOffice Notified: yes,
    Children Abducted Before: yes,
    Children Supervision: "yesSpendTime",
    yes No International Elements: yes,
    yes No Reasonable Adjustments: yes,
    Yes No Need Help With Fees: yes,
    Yes No Fees Applied: yes,
    @accessibilityCitizenFrontend
    `, async ({ page }): Promise<void> => {
    await C100.c100SecondMiroJourney({
      page: page,
      accessibilityTest: true,
      errorMessaging: true,
      c100LegalRepresentation: true,
      c100CourtPermissionNeeded: true,
      yesNoOtherProceedings: true,
      urgencyAndWithoutNoticeAllOptionsYes: true,
      gender: "male",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100OthersKnowApplicantsContact: "yes",
      c100PrivateDetails: true,
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "male",
      respondentChangedName: "yes",
      respAddress5Years: "yes",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "male",
      c100OtherPeopleChangedName: "yes",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100ChildMainlyLivesWith: "respondent",
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "noSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: true,
      c100YesNoFeesApplied: true,
    });
  });
  test(`Test the second row of the second row c100 citizen journey with the following options:
    Accessibility Testing,
    Yes Error Messaging,
    No Screening and Written Review
    Legal Representation: no
    Court Permission Needed: no
    Other proceedings: no to all
    child arrangement order details: no
    urgency and without notice: no
    gender: female
    People YesNoDontKnow: "no",
    Others Know Applicants Contact: "no",
    Private Details: yes,
    applicant Changed Name: no,
    applicant Gender: "other",
    applicant Relationship: "guardian",
    applicant Address Lookup: no,
    app Address Lookup Successful: no,
    applicant Prev Address 5Years: no,
    applicant Email Telephone Voicemail: no,
    applicant Digital Preference: no,
    respondent Known DoB: no,
    respondent Known Place Of Birth: no,
    respondent Gender: "female",
    respondent Changed Name: "no",
    resp Address 5Years: "no",
    respondent Relationship: "guardian",
    resp Address Lookup: no,
    resp Address Lookup Successful: no,
    resp Known Email And Phone: no,
    yes No Other Person Details: no,
    Other People Gender: "female",
    Other People Changed Name: "no",
    Other People DoB Known: no,
    Other Person Relationship: "guardian",
    Child Mainly Lives With: "respondent",
    Children Safety Concerns: no,
    Safety Concerns Yes NoToAll: no,
    Children Have Passport: no,
    More Than One Passport: no,
    PassportOffice Notified: no,
    Children Abducted Before: no,
    Children Supervision: "yesButSupervised",
    yes No International Elements: no,
    yes No Reasonable Adjustments: no,
    Yes No Need Help With Fees: no,
    Yes No Fees Applied: no,
    @accessibilityCitizenFrontend
    `, async ({ page }): Promise<void> => {
    await C100.c100SecondMiroJourney({
      page: page,
      accessibilityTest: true,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: false,
      yesNoOtherProceedings: false,
      urgencyAndWithoutNoticeAllOptionsYes: false,
      gender: "female",
      c100PeopleYesNoDontKnow: "no",
      c100OthersKnowApplicantsContact: "no",
      c100PrivateDetails: false,
      applicantChangedName: false,
      applicantGender: "female",
      applicantRelationship: "guardian",
      applicantAddressLookup: false,
      appAddressLookupSuccessful: false,
      applicantPrevAddress5Years: false,
      applicantEmailTelephoneVoicemail: false,
      applicantDigitalPreference: false,
      respondentKnownDoB: false,
      respondentKnownPlaceOfBirth: false,
      respondentGender: "female",
      respondentChangedName: "no",
      respAddress5Years: "no",
      respondentRelationship: "guardian",
      respAddressLookup: false,
      respAddressLookupSuccessful: false,
      respKnownEmailAndPhone: false,
      yesNoOtherPersonDetails: false,
      c100OtherPeopleGender: "female",
      c100OtherPeopleChangedName: "no",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "guardian",
      c100ChildMainlyLivesWith: "respondent",
      c100ChildrenSafetyConcerns: false,
      c100SafetyConcernsYesNoToAll: false,
      c100ChildrenHavePassport: false,
      c100MoreThanOnePassport: false,
      c100PassportOfficeNotified: false,
      c100ChildrenAbductedBefore: false,
      c100ChildrenSupervision: "yesButSupervised",
      yesNoInternationalElements: false,
      yesNoReasonableAdjustments: false,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });
});
