import { test } from "@playwright/test";
import IdamLoginHelper from "../../../../common/idamLoginHelper";
import Config from "../../../../config";
import { C100 } from "../../../../journeys/citizen/createCase/C100/C100";

test.describe("C100 Citizen Application with an existing MIAM document.", (): void => {
  test.beforeEach(async ({ page }) => {
    await IdamLoginHelper.signInCitizenUser(
      page,
      Config.citizenFrontendBaseURL,
    );
  });
  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with previously attended MIAM
  With a signed MIAM document
  urgency and without notice all options: no
  c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: true,
      documentSignedByMediator: true,
      miamValidReasonNoAttendance: false,
      miamGeneralExemptions: false,
      miamDomesticAbuse: false,
      miamDomesticAbuseProvidingEvidence: false,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "None of the above",
      miamReasonForNoAccessToMediator: "None of these",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Having attended a MIAM in the last 4 months
  With a mediator signed document
  urgency and without notice all options: no
  c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "Previous 4 months",
      miamPreviousAttendanceMediatorSignedDocument: true,
      miamOtherReasonForNotAttending: "None of the above",
      miamReasonForNoAccessToMediator: "None of these",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Having an application made in existing proceedings
  Without a mediator signed document
  urgency and without notice all options: no
   c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "Application made in existing proceedings",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "None of the above",
      miamReasonForNoAccessToMediator: "None of these",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Applying for an application without notice
  urgency and without notice all options: no
    c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Applying for without notice",
      miamReasonForNoAccessToMediator: "None of these",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Applying for an application for an U18 respondent
  urgency and without notice all options: no
    c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female, 
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Under 18",
      miamReasonForNoAccessToMediator: "None of these",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Cannot access mediator
  Unable to conduct within 15 days
  urgency and without notice all options: no
    c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Cannot access mediator",
      miamReasonForNoAccessToMediator: "Unable to conduct within 15 days",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Cannot access mediator
  Disability
  urgency and without notice all options: no
  c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Cannot access mediator",
      miamReasonForNoAccessToMediator: "Disability",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Cannot access mediator
  No mediator within 15 miles
  urgency and without notice all options: no
  c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Cannot access mediator",
      miamReasonForNoAccessToMediator: "No mediator within 15 miles",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Cannot access mediator
  Prison or institution
  urgency and without notice all options: no
  c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @nightly`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Cannot access mediator",
      miamReasonForNoAccessToMediator: "Prison or institution",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Cannot access mediator
  subject to bail
  urgency and without notice all options: no
  c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Cannot access mediator",
      miamReasonForNoAccessToMediator: "Subject to bail",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  //
  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Cannot access mediator
  released from prison on license
  urgency and without notice all options: no
  c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Cannot access mediator",
      miamReasonForNoAccessToMediator: "Released from prison on license",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Error Messaging
  MIAM testing with a valid reason for not attending
  With a signed document
  urgency and without notice all options: no
    c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @errorMessage`, async ({
                                                                page,
                                                              }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: true,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: true,
      documentSignedByMediator: true,
      miamValidReasonNoAttendance: false,
      miamGeneralExemptions: false,
      miamDomesticAbuse: false,
      miamDomesticAbuseProvidingEvidence: false,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "None of the above",
      miamReasonForNoAccessToMediator: "None of these",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Not Accessibility Testing
  Error Messaging
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Cannot access mediator
  released from prison on license
  urgency and without notice all options: no
    c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @regression @errorMessage`, async ({
                                                                page,
                                                              }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: false,
      errorMessaging: true,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Cannot access mediator",
      miamReasonForNoAccessToMediator: "Released from prison on license",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });
});

test.describe("C100 Citizen Application accessibility tests on the third row journey set. @accessibility", (): void => {
  test.beforeEach(async ({ page }) => {
    await IdamLoginHelper.signInCitizenUser(
      page,
      Config.citizenFrontendBaseURL,
    );
  });
  test(`C100 Citizen Application with the following options:
  Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With a signed document
  urgency and without notice all options: no
    c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @accessibility`, async ({ page }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: true,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: true,
      documentSignedByMediator: true,
      miamValidReasonNoAttendance: false,
      miamGeneralExemptions: false,
      miamDomesticAbuse: false,
      miamDomesticAbuseProvidingEvidence: false,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "None of the above",
      miamReasonForNoAccessToMediator: "None of these",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });

  test(`C100 Citizen Application with the following options:
  Accessibility Testing
  Not Error Messaging
  Legal Representation
  No Permission Needed
  MIAM testing with a valid reason for not attending
  With all general MIAM exemptions
  And subject to domestic abuse
  providing evidence of domestic abuse
  Cannot access mediator
  released from prison on license
  urgency and without notice all options: no
  c100PeopleGender: 'other'
  c100PeopleYesNoDontKnow: no
  keep details private: false,
  applicantChangedName: true,
  applicantGender: 'other',
  applicantRelationship: special guardian,
  applicant lives in a refuge: no,
  applicant address lookup: false,
  applicant address lookup successful: false,
  applicant lived at address more than 5 years: false,
  applicant email and telephone: false,
  applicant digital preferences: false,
  respondent DoB false,
  respondent place of birth false,
  respondent gender: female,
  respondent changed name: no,
  respondent lived aat address less than 5 years: no,
  respondent relationship: special guardian,
  respondent address lookup: false,
  respondent address lookup successful: false,
  respondent known contacts: no,
  Other Person details: false,
  Other person gender: female,
  Other person changed name: no,
  other person birthday known: false,
  other person relationship: special guardian,
  other person lives in a refuge: no,
  child mainly lives with: applicant,
  other proceedings radios: false,
  safety concerns : false,
  safety concerns : false,
  children have passport: false,
  more than one passport: false,
  passport office notified: no,
  children abducted before: no,
  child supervision: yes spend time,
  international elements : false,
  reasonable adjustments: false,
  need help with fees: no,
  fees applied: no @accessibility @nightly`, async ({
                                                              page,
                                                            }): Promise<void> => {
    await C100.c100CAExistingMIAMDocumentJourney({
      page: page,
      accessibilityTest: true,
      errorMessaging: false,
      c100LegalRepresentation: false,
      c100CourtPermissionNeeded: true,
      miamAlreadyAttended: false,
      documentSignedByMediator: false,
      miamValidReasonNoAttendance: true,
      miamGeneralExemptions: true,
      miamDomesticAbuse: true,
      miamDomesticAbuseProvidingEvidence: true,
      miamChildProtectionConcernsType: "None of the above",
      miamUrgencyType: "None of these",
      miamAttendanceType: "None of these",
      miamPreviousAttendanceMediatorSignedDocument: false,
      miamOtherReasonForNotAttending: "Cannot access mediator",
      miamReasonForNoAccessToMediator: "Released from prison on license",
      urgencyAndWithoutNoticeAllOptionsYes: false,
      c100PeopleGender: "female",
      c100PeopleYesNoDontKnow: "dontKnow",
      c100PrivateDetails: true,
      c100OthersKnowApplicantsContact: "dontKnow",
      applicantChangedName: true,
      applicantGender: "other",
      applicantRelationship: "specialGuardian",
      applicantLivesInRefuge: false,
      applicantAddressLookup: true,
      appAddressLookupSuccessful: true,
      applicantPrevAddress5Years: true,
      applicantEmailTelephoneVoicemail: true,
      applicantDigitalPreference: true,
      respondentKnownDoB: true,
      respondentKnownPlaceOfBirth: true,
      respondentGender: "other",
      respondentChangedName: "dontKnow",
      respAddress5Years: "dontKnow",
      respondentRelationship: "specialGuardian",
      respAddressLookup: true,
      respAddressLookupSuccessful: true,
      respKnownEmailAndPhone: true,
      yesNoOtherPersonDetails: true,
      c100OtherPeopleGender: "other",
      c100OtherPeopleChangedName: "dontKnow",
      c100OtherPeopleDoBKnown: true,
      c100OtherPersonRelationship: "specialGuardian",
      c100OtherPersonLivesInRefuge: false,
      c100ChildMainlyLivesWith: "otherPerson",
      yesNoChildArrangementOrderDetails: true,
      yesNoOtherProceedings: true,
      c100ChildrenSafetyConcerns: true,
      c100SafetyConcernsYesNoToAll: true,
      c100ChildrenHavePassport: true,
      c100MoreThanOnePassport: true,
      c100PassportOfficeNotified: true,
      c100ChildrenAbductedBefore: true,
      c100ChildrenSupervision: "yesSpendTime",
      yesNoInternationalElements: true,
      yesNoReasonableAdjustments: true,
      c100YesNoNeedHelpWithFees: false,
      c100YesNoFeesApplied: false,
    });
  });
});