export enum CommonStaticText {
  saveAndComeBackLater = "Save and come back later",
  yes = "Yes",
  no = "No",
  dontKnow = "Don't know",
  continue = "Continue",
  submit = "Submit",
  previous = "Previous",
  errorSummaryTitle = " There is a problem on this page ",
  day = "Day",
  month = "Month",
  year = "Year",
  uploadAFile = "Upload a file",
  uploadFile = "Upload file",
  remove = "Remove",
  mother = "Mother",
  father = "Father",
  other = "Other",
  selectAllThatApply = "Select all that apply",
  provideMoreDetails = "Provide more details",
}
